# Generated by Django 5.1 on 2024-11-18 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0002_reserva_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='imagen',
            field=models.URLField(blank=True, null=True),
        ),
    ]
