# Generated by Django 5.1 on 2024-11-18 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0003_pelicula_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoConfiteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
