# Generated by Django 5.1 on 2024-11-18 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0005_codigopromocional'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='total_pagado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
