# Generated by Django 5.1 on 2024-11-19 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0006_reserva_total_pagado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='capacidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sala',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='cine.pelicula')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='cine.sala')),
            ],
        ),
    ]
