# Generated by Django 5.1 on 2024-11-19 18:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0007_alter_sala_capacidad_alter_sala_numero_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
