# Generated by Django 5.1 on 2024-11-19 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0008_horario_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='sala',
        ),
        migrations.AddField(
            model_name='reserva',
            name='horario',
            field=models.ForeignKey(default=-10, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='cine.horario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_reserva',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
