# Generated by Django 5.1 on 2024-11-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0009_remove_reserva_sala_reserva_horario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='horario',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
